// eslint-disable-next-line no-undef
export default AppConstants = {
  DEBIT_CARD: 'Debit Card',
  AVL_BALANCE: 'Available Balance',
  DOLLAR: 'S$',
  SPENDING_LIMIT: 'Spending Limit',
  DEBIT_CARD_LIMIT: 'Debit card spending limit',
  TOP_UP_ACC: 'Top-up account',
  DEPOSIT_MONEY_ACC: 'Deposit money to your account to use with card',
  YOUR_WEEKELY_SPENDING: 'Your weekly spending limit is',
  WEEKELY_SPENDING_LIMIT: 'Weekly spending limit',
  FREEZE_CARD: 'Freeze card',
  YOUR_DEBIT_CARD_ACTIVE: 'Your debit card is currently active',
  GET_NEW_CARD: 'Get a new card',
  DEACTIVATE_CURRENT_CARD: 'This deactivates your current debit card',
  DEACTIVATED_CARD: 'Deactivated cards',
  PREVIUOS_DEACTIVATED_CARD: 'Your previously deactivated cards',
  SET_WEEKELY_DEBIT_LIMIT: 'Set a weekly debit card spending limit',
  HERE_WEEKELY_MEANS:
    'Here weekly means the last 7 days - not the calendar week',
  SAVE: 'Save',
  NAME: 'Mark Henry',
  SHOW_CARD_NUMBER: 'Show card number',
  HIDE_CARD_NUMBER: 'Hide card number',
  CARD_NUMBER: '5647    3411    2413    2020',
  CARD_NUMBER_HIDE: '****    ****    ****    2020',
  CVV: 456,
  CVV_HIDE: '***',
  EXPIRY_DATE: '12/23'
};
